version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-svc
    environment:
      - POSTGRESQL_DATABASE=sneaker-store
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    container_name: redis-svc
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_PORT_NUMBER=7000
    ports:
      - '7000:7000'

  django:
    build: ./backend/django-api
    container_name: django-svc
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/django-api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  react:
    build: ./frontend
    container_name: react
    ports:
      - "8080:8080"
    depends_on:
      - django
  grafana:
    image: bitnami/grafana:9.5.2
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "bitnami"
      GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8080/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
    volumes:
      - grafana_data:/opt/bitnami/grafana

volumes:
  postgres_data:
  grafana_data: