version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=sneaker-store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6
    container_name: redis

  django:
    build: ./backend/django-api
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/django-api:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  react:
    build: ./frontend
    container_name: react
    ports:
      - "8080:8080"
    depends_on:
      - django

volumes:
  postgres_data: