# Generated by Django 4.0.1 on 2022-01-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.BinaryField(),
            preserve_default=False,
        ),
    ]
