# Generated by Django 4.1 on 2023-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_product_inserts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
