apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: gic-group-9
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: registry.deti:5000/gic/g9/django:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000