apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: gic-group-9
spec:
  selector:
    matchLabels:
      app: django
  replicas: 3
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: registry.deti:5000/gic/g9/django:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_SECRET_KEY
        - name: POSTGRES_DBNAME
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_DBNAME
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: REDIS_PASSWORD
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 50
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 50
          periodSeconds: 10