apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: gic-group-9
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP