apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: gic-group-9
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  type: ClusterIP