apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: gic-group-9
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /bitnami/postgresql"]
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgres-data
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DBNAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_DBNAME
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host localhost
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host localhost
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
