apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: gic-group-9
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 7000
          env:
            - name: REDIS_PASSWORD
              value: password123
            - name: REDIS_PORT_NUMBER
              value: "7000"
