apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: gic-group-9
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 7000
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_PORT_NUMBER
              value: "7000"